### ISSUE TITLE
Complete blank page on windows 7

### ISSUE THREAD

**Issue by gryBox** [mmowers/superpivot#1]
Hi - Super excited to see this.  I tried running it on Windows 7, bokeh 12.3 python 3.5

This is my screenshot
![image](https://cloud.githubusercontent.com/assets/16763201/21563158/895169ac-ce44-11e6-98ed-265528c04c61.png)

The console is showing this 
![image](https://cloud.githubusercontent.com/assets/16763201/21563206/29ee07bc-ce45-11e6-92ab-c17dec7b7cb8.png)

Any suggestions?

**Comment by mmowers** [comment]
hi @gryBox , sorry for the late reply, I completely missed this. If you refresh the page, does the connection close again? Maybe chrome inspector console would show an error too? FYI, I'm hoping to contribute this to bokeh's main github repo as an app example (https://github.com/bokeh/bokeh/tree/master/examples/app). See https://github.com/bokeh/bokeh/issues/5640. Thanks for your issue report!

**Comment by afonit** [comment]
@gryBox did you include the trailing period in the command in the run instructions?  I did that once and it looked exactly like what you are showing.

**Comment by gryBox** [comment]
@mmowers Strange.  I tried it on my home machine - It worked.   FWIW: I think this would be great in the Bokeh docs.  It is really neat.  I can see a lot of people using this as template to explore data.

Thanks for following up

**Comment by mmowers** [comment]
@afonit found the issue. A period is needed at the end of the command:
`bokeh serve --show .`
Closing this now.
Thanks again!
